nrdb-01.gbnet:
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: dba
  password:
  host: 127.0.0.1
  port: 3306
  socket: /var/lib/mysql/mysql.sock
  database:

sadb-01:
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password:
  host: 127.0.0.1
  port: 3306
  socket: /var/lib/mysql/mysql.sock
  database:
